### ISSUE TITLE
ASP.NET Core file loader

### ISSUE THREAD

**Issue by snboisen** [StubbleOrg/Stubble.Extensions.Loaders#2]
I wanted a template loader that integrated well with ASP.NET Core, so I wrote one myself.

It probably does not belong in this package, since it would add a dependency on ASP.NET Core packages. But since I like the Stubble project and it appears to currently be the only mustache template library available for .NET Core, I thought I would contribute a little back 😃 

```C#
using System.Collections.Concurrent;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Options;
using Stubble.Core.Interfaces;

namespace TeamString.Admin.Email
{
    /// <summary>
    /// A template loader for Stubble that locates templates based on a base path relative to the
    /// webapp content root. This loader integrates much better with ASP.NET Core apps than the
    /// FileSystemLoader provided in Stubble extensions.
    /// </summary>
    public sealed class AspNetCoreTemplateLoader : IStubbleLoader
    {
        private readonly string templateBasePath;
        private readonly ConcurrentDictionary<string, string> templateCache;

        public AspNetCoreTemplateLoader(IOptions<StubbleOptions> options, IHostingEnvironment hostEnv)
        {
            this.templateBasePath = Path.Combine(hostEnv.ContentRootPath, options.Value.TemplateBasePath);
            this.templateCache = new ConcurrentDictionary<string, string>();
        }

        private AspNetCoreTemplateLoader(string templateBasePath, ConcurrentDictionary<string, string> templateCache)
        {
            this.templateBasePath = templateBasePath;
            this.templateCache = templateCache;
        }

        public IStubbleLoader Clone()
        {
            return new AspNetCoreTemplateLoader(templateBasePath, templateCache);
        }

        public string Load(string name)
        {
            string template = null;
            if (!templateCache.TryGetValue(name, out template))
            {
                template = LoadTextFile(name);
                templateCache.AddOrUpdate(name, template, (k, v) => template);
            }

            return template;
        }

        public ValueTask<string> LoadAsync(string name)
        {
            string template = null;
            if (templateCache.TryGetValue(name, out template))
            {
                return new ValueTask<string>(template);
            }
            else
            {
                return new ValueTask<string>(LoadFromFileAsync(name));
            }
        }

        // TODO: Move this method inside LoadAsync as a local function once we move to C# 7
        // See: http://thebillwagner.com/Blog/Item/2016-03-02-C7FeatureProposalLocalFunctions
        private async Task<string> LoadFromFileAsync(string name)
        {
            string template = await LoadTextFileAsync(name);
            templateCache.AddOrUpdate(name, template, (k, v) => template);
            return template;
        }

        private string GetFullPath(string templateName) => Path.Combine(templateBasePath, templateName);

        private string LoadTextFile(string templateName) => File.ReadAllText(GetFullPath(templateName), Encoding.UTF8);

        private async Task<string> LoadTextFileAsync(string templateName)
        {
            using (var file = new FileStream(GetFullPath(templateName), FileMode.Open, FileAccess.Read, FileShare.Read, bufferSize: 4096, useAsync: true))
            using (var reader = new StreamReader(file, Encoding.UTF8, detectEncodingFromByteOrderMarks: false, bufferSize: 4096, leaveOpen: true))
            {
                return await reader.ReadToEndAsync();
            }
        }
    }
}
```

**Comment by Romanx** [comment]
Hi there,

Thank you for posting this, I love the look of it and it's more up to date than the ones currently in this repo. Would you mind me taking this and perhaps building a version of `Stubble.Extensions.Loaders` that cross compiles to dotnet core with a version of this being added?

I'd completely forgotten I'd changed the IStubbleLoader interface and not updated these templates so i'm going to create an issue for that now.

**Comment by snboisen** [comment]
I don't mind at all. I posted it in the hope it would be useful to others, so if you can make use of it... 👍 👍 

Yeah, I was a bit confused when I noticed that the existing implementations didn't match the interface hehe.

**Comment by Romanx** [comment]
Excellent. I'll leave this open until i've integrated it into the repo. Please feel free to post any issues or features you like with Stubble. I'm currently using it in production and when I think it's stable then i'll make a 1.0 release finally.

**Comment by Romanx** [comment]
Hi @snboisen. I've just made a new release of this package including updates loaders with the async implementations. At the same time I took a look at the flaws in the `FileSystemLoader` and decided to unify some of the features with yours. Here are some of the highlights:

- The need for the extension has been removed, you can pass `null` or `string.Empty` to have the loader assume the partial name is exactly the same as the file.
- If your partial name is already delimited by the standard directory separator character for your platform and you set it as the delimiter replacing the delimiter is skipped.

These changes all seem to make the loader a little more general purpose and should make it easier to implement your `AspNetCoreTemplateLoader` by just inheriting from the `FileSystemLoader` and providing your own constructor. It would like something like this (note the use of an empty string to assume the file extension is in the partial name)

```c#
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Options;
using Stubble.Extensions.Loaders;

namespace TeamString.Admin.Email
{
    /// <summary>
    /// A template loader for Stubble that locates templates based on a base path relative to the
    /// webapp content root. This loader integrates much better with ASP.NET Core apps than the
    /// FileSystemLoader provided in Stubble extensions.
    /// </summary>
    public sealed class AspNetCoreTemplateLoader : FileSystemLoader
    {
        public AspNetCoreTemplateLoader(IOptions<StubbleOptions> options, IHostingEnvironment hostEnv)
            : base(Path.Combine(hostEnv.ContentRootPath, options.Value.TemplateBasePath), "")
        {
        }
    }
}
```

I'm going to close this issue now as I think this is a fair enhancement on what I originally had and allows a simplification of your use case. Please let me know if you have any other quirks or sources of frustration.
